DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS clubs CASCADE;
DROP TABLE IF EXISTS members CASCADE; 
DROP TABLE IF EXISTS club_admins CASCADE; 
DROP TABLE IF EXISTS club_managers CASCADE; 
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS comments CASCADE;